import Layout from "@/components/Layout"
import Head from "next/head"

const About = () => {
  return (
    <Layout>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      Hello
    </Layout>
  )
}

export default About
